import re

with open(r'Y:\btcsolver\static\dashboard\app.js', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    # vaultKeyActions - button titles and labels
    ("Copier la cl\u00e9 priv\u00e9e (hex 64) \u2014 rester en local, ne jamais coller dans un navigateur web",
     "Copy private key (hex 64) \u2014 stay local, never paste into a web browser"),
    ("\u269b\ufe0f Copier PRIV",
     "\u269b\ufe0f Copy PRIV"),
    ("Copier l\u2019adresse publique (format court pour explorers)",
     "Copy public address (short format for explorers)"),
    ("\U0001f7e9 Copier ADDR",
     "\U0001f7e9 Copy ADDR"),
    ("Cl\u00e9 publique compress\u00e9e courte (02/03\u2026, 33 octets)",
     "Short compressed public key (02/03\u2026, 33 bytes)"),
    ("Copier PUB hex",
     "Copy PUB hex"),
    ("pas d\u2019adresse publique pour explorer",
     "no public address to explore"),

    # renderFound - empty state
    ("Aucune cl\u00e9 sauv\u00e9e. Fais un test qui trouve un solde, puis \u00ab Sauver les hits \u00bb. Les pubkeys sont d\u00e9riv\u00e9es auto pour coller sur un explorer.",
     "No keys saved. Run a test that finds a balance, then \u00ab Save hits \u00bb. Pubkeys are auto-derived to paste into an explorer."),
    ("Pr\u00e9paration des cl\u00e9s publiques\u2026",
     "Preparing public keys\u2026"),
    ("entr\u00e9e",
     "input"),
    ("adresse publique",
     "public address"),
    ("priv hex",
     "priv hex"),
    ("pub hex (comp courte)",
     "pub hex (short comp)"),
    ("sauv\u00e9",
     "saved"),
    ("Retirer",
     "Remove"),

    # Key check form
    ("Vide",
     "Empty"),
    ("Lot de",
     "Batch of"),
    ("Test\u2026",
     "Testing\u2026"),
    ("candidats \u00b7 total",
     "candidates \u00b7 total"),
    ("hits",
     "hits"),
    ("0 hit affich\u00e9 (candidats:",
     "0 hit shown (candidates:"),
    ("D\u00e9coche \u00ab Seulement soldes > 0 \u00bb pour voir les adresses \u00e0 0.",
     "Uncheck \u00ab Only balances > 0 \u00bb to see zero-balance addresses."),
    ("priv hex (64)",
     "priv hex (64)"),
    ("cl\u00e9 publique (pub hex)",
     "public key (pub hex)"),
    ("adresse",
     "address"),
    ("cl\u00e9 trouv\u00e9e !",
     "key found!"),
    ("cl\u00e9(s) au total",
     "key(s) total"),
    ("cl\u00e9 avec activit\u00e9/solde",
     "key with activity/balance"),
    ("Nouveau hit \u2014 total",
     "New hit \u2014 total"),
    ("cl\u00e9(s) actives (solde ou historique)",
     "active key(s) (balance or history)"),
    ("Aucune cl\u00e9 avec activit\u00e9 on-chain",
     "No key with on-chain activity"),
    ("solde \u00b7",
     "balance \u00b7"),
    ("activit\u00e9 sans solde \u00b7 archive data/keys-archive.json",
     "activity without balance \u00b7 archive data/keys-archive.json"),
    ("aucune cl\u00e9 avec activit\u00e9 on-chain pour l\u2019instant",
     "no key with on-chain activity yet"),

    # Mode buttons
    ("Mode MAX activ\u00e9",
     "MAX mode activated"),
    ("Mode rapide",
     "Fast mode"),
    ("Aucun test pour l\u2019instant.",
     "No test yet."),

    # Dict
    ("Mo)",
     "MB)"),
    ("(\u2014 (options off : 1 phrase / ligne seulement)",
     "(\u2014 (options off: 1 phrase/line only)"),
    ("phrases base (n=",
     "base phrases (n="),
    ("mots)",
     "words)"),
    (" \u26a0 volumineux",
     " \u26a0 large"),
    (" \u00b7 moyen",
     " \u00b7 medium"),
    (" \u00b7 l\u00e9ger",
     " \u00b7 light"),
    ("affixes : off",
     "affixes: off"),
    (" \u00b7 tr\u00e8s long (streaming, pas de plafond)",
     " \u00b7 very long (streaming, no ceiling)"),
    (" \u00b7 long (boucles streaming)",
     " \u00b7 long (streaming loops)"),
    ("affixes :",
     "affixes:"),
    ("D\u00e9marrage\u2026",
     "Starting\u2026"),
    ("Scan lanc\u00e9",
     "Scan started"),
    ("Scan dictionnaire d\u00e9marr\u00e9",
     "Dictionary scan started"),
    ("Arr\u00eat demand\u00e9",
     "Stop requested"),

    # Status bar
    ("Scan de fond arr\u00eat\u00e9",
     "Background scan stopped"),
    ("test\u00e9es:",
     "tested:"),
    ("Cha\u00eene OK",
     "Chain OK"),
    ("Cha\u00eene \u00e0 jour",
     "Chain up to date"),
    ("Cha\u00eene sync",
     "Chain syncing"),
    ("Sync en cours",
     "Sync in progress"),
    ("Cha\u00eene off",
     "Chain off"),
    ("Core arr\u00eat\u00e9",
     "Core stopped"),
    ("Index charg\u00e9 \u00b7",
     "Index loaded \u00b7"),
    ("scripts",
     "scripts"),
    ("Index en chargement",
     "Index loading"),
    ("Tester des mots = onglet 1",
     "Test words = tab 1"),

    # UTXO tip warning
    ("index UTXO bloc",
     "UTXO index block"),
    ("/ Core tip",
     "/ Core tip"),
    ("(retard",
     "(lag"),
    ("blocs",
     "blocks"),
    ("index UTXO: hauteur inconnue",
     "UTXO index: unknown height"),
    ("reindex/IBD",
     "reindex/IBD"),
    ("Core: ?",
     "Core: ?"),
    ("tests OK)",
     "tests OK)"),
    ("tests non fiables)",
     "tests unreliable)"),
    ("blocs derri\u00e8re le tip",
     "blocks behind tip"),
    ("\u2713 UTXO au tip \u2014 soldes fiables pour les tests",
     "\u2713 UTXO at tip \u2014 balances reliable for tests"),
    ("\u2713 UTXO valable pour les tests (<",
     "\u2713 UTXO valid for tests (<"),
    ("h du tip)",
     "h of tip)"),
    ("Index UTXO au bloc",
     "UTXO index at block"),
    ("tip Core",
     "tip Core"),
    ("L\u2019index est \u00e0 moins de",
     "Index is within"),
    ("h",
     "h"),
    ("du tip estim\u00e9",
     "of estimated tip"),
    ("(retard \u2248",
     "(lag \u2248"),
    ("Tu peux t\u2019en servir pour tester des cl\u00e9s / brainwallets.",
     "You can use it to test keys / brainwallets."),
    ("V\u00e9rifie quand m\u00eame on-chain avant toute d\u00e9pense.",
     "Verify on-chain before any spending."),
    ("valable tests (<",
     "valid for tests (<"),
    ("h)",
     "h)"),
    ("Index bloc",
     "Index block"),
    ("\u26a0 Bitcoin Core arr\u00eat\u00e9 \u2014 red\u00e9marrage automatique\u2026",
     "\u26a0 Bitcoin Core stopped \u2014 auto-restarting\u2026"),
    ("\u23f3 Core synchronise la cha\u00eene \u2014 UTXO tip en attente (normal)",
     "\u23f3 Core syncing chain \u2014 UTXO tip pending (normal)"),
    ("\u26a0 UTXO bloc",
     "\u26a0 UTXO block"),
    ("trop vieux pour des soldes fiables",
     "too stale for reliable balances"),
    ("inconnu",
     "unknown"),
    ("Le watchdog <code>Keep-Core-And-Utxo</code> doit relancer bitcoind sous peu.",
     "The watchdog <code>Keep-Core-And-Utxo</code> will restart bitcoind shortly."),
    ("S\u2019il reste arr\u00eat\u00e9 : lance <code>Install-AlwaysOn.bat</code> ou <code>Launch-BitcoinCore.ps1</code>.",
     "If it stays stopped: run <code>Install-AlwaysOn.bat</code> or <code>Launch-BitcoinCore.ps1</code>."),
    ("<strong>Bitcoin Core fonctionne</strong> et rattrape le tip :",
     "<strong>Bitcoin Core is running</strong> and catching up to tip:"),
    ("blocs",
     "blocks"),
    ("Index UTXO actuel : bloc",
     "Current UTXO index: block"),
    ("L\u2019index UTXO offline ne peut \u00eatre r\u00e9g\u00e9n\u00e9r\u00e9 au tip <em>que</em> quand Core a fini (IBD = non).",
     "The offline UTXO index can be regenerated at tip <em>only</em> when Core has finished (IBD = false)."),
    ("Auto-refresh : t\u00e2che <code>BTCSolver-Core-Utxo</code> (dumptxoutset d\u00e8s le tip).",
     "Auto-refresh: task <code>BTCSolver-Core-Utxo</code> (dumptxoutset at tip)."),
    ("<br>En attendant : tests = <em>candidats seulement</em> (retard UTXO \u2248",
     "<br>In the meantime: tests = <em>candidates only</em> (UTXO lag \u2248"),
    ("<strong>Ne coupe pas bitcoind.</strong>",
     "<strong>Do not stop bitcoind.</strong>"),
    ("R\u00e8gle : index UTXO <strong>valable pour les tests</strong> seulement s\u2019il a",
     "Rule: UTXO index <strong>valid for tests</strong> only if it has"),
    ("de retard sur le tip.",
     "lag behind tip."),
    ("Actuellement retard \u2248",
     "Current lag \u2248"),
    ("Les hits restent des <em>candidats</em>.",
     "Hits remain <em>candidates</em>."),
    ("<br>Refresh auto au tip via <code>Keep-Core-And-Utxo.ps1</code>.",
     "<br>Auto-refresh at tip via <code>Keep-Core-And-Utxo.ps1</code>."),

    # Btc status
    ("En ligne",
     "Online"),
    ("Process",
     "Process"),
    ("Arr\u00eat\u00e9",
     "Stopped"),
    ("oui",
     "yes"),
    ("non",
     "no"),

    # Badge status
    ("Core lent \u00b7",
     "Core slow \u00b7"),
    ("Core lent",
     "Core slow"),
    ("Tip Core il y a",
     "Core tip from"),
    ("h (dernier bloc > 1 h)",
     "h ago (last block > 1h)"),
    ("Core ON \u00b7",
     "Core ON \u00b7"),
    ("Core ON",
     "Core ON"),
    ("Bitcoin Core en marche \u00b7 tip bloc",
     "Bitcoin Core running \u00b7 tip block"),
    ("Bitcoin Core en marche",
     "Bitcoin Core running"),
    ("Core OFF",
     "Core OFF"),
    ("Bitcoin Core arr\u00eat\u00e9 \u2014 soldes/tip non fiables",
     "Bitcoin Core stopped \u2014 balances/tip unreliable"),
    ("Core \u00b7 ?",
     "Core \u00b7 ?"),
    ("\u00c9tat Core inconnu",
     "Core state unknown"),
    ("UTXO \u00b7 ?",
     "UTXO \u00b7 ?"),
    ("Fra\u00eecheur UTXO inconnue",
     "UTXO freshness unknown"),
    ("UTXO rebuild\u2026 \u00b7",
     "UTXO rebuild\u2026 \u00b7"),
    ("UTXO rebuild\u2026",
     "UTXO rebuild\u2026"),
    ("Recr\u00e9ation de l\u2019index en cours (dumptxoutset / dump_to_flat) \u2014 pas encore rouge",
     "Index rebuild in progress (dumptxoutset / dump_to_flat) \u2014 not yet red"),
    ("UTXO OK \u00b7",
     "UTXO OK \u00b7"),
    ("UTXO OK (< 24 h)",
     "UTXO OK (< 24 h)"),
    ("Index \u00e0 jour (<",
     "Index up to date (<"),
    ("h du tip) \u00b7 retard \u2248",
     "h of tip) \u00b7 lag \u2248"),
    ("UTXO vieux \u00b7",
     "UTXO stale \u00b7"),
    ("UTXO vieux (",
     "UTXO stale ("),
    ("Retard \u2248",
     "Lag \u2248"),
    ("et aucune recr\u00e9ation en cours",
     "and no rebuild in progress"),
    ("Retard",
     "Lag"),
    ("(< ~24 h)",
     "(< ~24 h)"),
    ("(",
     "("),
    ("pas de rebuild",
     "no rebuild"),

    # UTXO display
    ("Index UTXO = bloc",
     "UTXO index = block"),
    ("Bitcoin Core tip = bloc",
     "Bitcoin Core tip = block"),
    ("retard",
     "lag"),
    ("(tip Core inconnu)",
     "(Core tip unknown)"),
    ("Core tip: (inconnu \u2014 Core offline ?)",
     "Core tip: (unknown \u2014 Core offline?)"),
    ("Core tip: \u2014",
     "Core tip: \u2014"),
    ("bloc \u2014",
     "block \u2014"),
    ("date du bloc:",
     "block date:"),
    ("(indisponible \u2014 Core pas au tip / reindex)",
     "(unavailable \u2014 Core not at tip / reindex)"),
    ("index g\u00e9n\u00e9r\u00e9:",
     "index generated:"),
    ("hash:",
     "hash:"),
    ("UTXO \u2026",
     "UTXO \u2026"),
    ("index bloc",
     "index block"),
    ("Core tip",
     "Core tip"),
    ("\u00e2ge fichier",
     "file age"),
    ("h",
     "h"),

    # Scan
    ("vitesses par carte en attente\u2026",
     "per-card speeds pending\u2026"),
    ("plage(s) journalis\u00e9e(s)",
     "range(s) logged"),
    ("De copi\u00e9",
     "From copied"),
    ("\u00c0 copi\u00e9",
     "To copied"),
    ("Scan en cours\u2026",
     "Scan in progress\u2026"),
    ("Scan arr\u00eat\u00e9 \u2014 se relance auto si GPU libre (pas de scan listes)",
     "Scan stopped \u2014 auto-restarts if GPU free (no list scan)"),
    ("De (d\u00e9part fen\u00eatre \u2014 hex complet)",
     "From (window start \u2014 full hex)"),
    ("De (min threads \u2014 hex complet)",
     "From (min threads \u2014 full hex)"),
    ("\u00c0 (fin fen\u00eatre \u2014 hex complet)",
     "To (window end \u2014 full hex)"),
    ("\u00c0 (max threads \u2014 hex complet)",
     "To (max threads \u2014 full hex)"),
    ("ARR\u00cAT\u00c9 (auto GPU idle)",
     "STOPPED (auto GPU idle)"),
    ("Pas de process brute \u2014 red\u00e9marrage auto ~15 s si pas de scan listes GPU",
     "No brute process \u2014 auto-restart ~15s if no GPU list scan"),
    ("RANDOM \u00b7 live",
     "RANDOM \u00b7 live"),
    ("Random : De/\u00c0 = min\u2192max des derni\u00e8res cl\u00e9s des threads (\u00e9chantillons, pas une plage continue)",
     "Random: From/To = min\u2192max of last thread keys (samples, not a continuous range)"),
    ("mode: RANDOM",
     "mode: RANDOM"),
    ("S\u00c9QUENTIEL \u00b7 live",
     "SEQUENTIAL \u00b7 live"),
    ("S\u00e9quentiel : fen\u00eatre De \u2192 \u00c0",
     "Sequential: window From \u2192 To"),
    ("cl\u00e9s / pas). Curseur live plus bas. Journal = pas de retest.",
     "keys/step). Live cursor below. Log = no retest."),
    ("S\u00e9quentiel : d\u00e9part fen\u00eatre \u2192 fin fen\u00eatre (pas 2^30 par d\u00e9faut)",
     "Sequential: window start \u2192 window end (step 2^30 default)"),
    ("mode: S\u00c9QUENTIEL",
     "mode: SÉQUENTIAL"),
    ("actif",
     "active"),
    ("mode: actif",
     "mode: active"),

    # CPU threads hint
    ("workers forc\u00e9s (threads fixes) \u00b7",
     "forced workers (fixed threads) \u00b7"),
    ("c\u0153urs d\u00e9tect\u00e9s",
     "cores detected"),
    ("worker CPU (GPU only) \u00b7",
     "CPU worker (GPU only) \u00b7"),
    ("c\u0153urs",
     "cores"),
    ("workers CPU",
     "CPU workers"),
    ("actif par d\u00e9faut",
     "active by default"),

    # Ranges log
    ("Aucune plage termin\u00e9e \u2014 le journal se remplit quand un \u00c0 est atteint.",
     "No range completed \u2014 log fills when a To is reached."),
    ("De",
     "From"),
    ("\u00c0",
     "To"),
    ("cl\u00e9s \u00b7",
     "keys \u00b7"),

    # Misc
    ("Hex de d\u00e9part requis",
     "Start hex required"),
    ("D\u00e9part appliqu\u00e9 \u2014 scan relanc\u00e9",
     "Start applied \u2014 scan restarted"),
    ("D\u00e9part enregistr\u00e9 (prochain d\u00e9marrage)",
     "Start saved (next start)"),
    ("Pas enregistr\u00e9 :",
     "Step saved:"),
    ("Scan d\u00e9marr\u00e9 \u00b7",
     "Scan started \u00b7"),
    ("workers CPU",
     "CPU workers"),
    ("Arr\u00eat demand\u00e9",
     "Stop requested"),
    ("Live",
     "Live"),
    ("Core: inaccessible",
     "Core: inaccessible"),
    ("\u00c9chec index",
     "Index failed"),
    ("Rebuild UTXO (tr\u00e8s long) ?",
     "Rebuild UTXO (very long)?"),
    ("OK \u2014 recharge l\u2019index",
     "OK \u2014 reloading index"),
    ("Relance",
     "Restart"),
    ("API indisponible",
     "API unavailable"),
    ("timeout",
     "timeout"),
    ("fichier ~",
     "file ~"),
]

count = 0
for old, new in replacements:
    if old in content:
        content = content.replace(old, new)
        count += 1
    else:
        print(f"NOT FOUND: {old[:60]}")

print(f"\nReplaced {count} strings")

with open(r'Y:\btcsolver\static\dashboard\app.js', 'w', encoding='utf-8') as f:
    f.write(content)
